### ISSUE TITLE
Server Selection vanishes when selecting specific server

### ISSUE THREAD

**Issue by riley-hayes** [JLyne/LiveAtlas#99] opened 2021-08-29 12:35 UTC
I don't know what I did, but while adding servers into the index.html document, I somehow broke the server selection menu with only one server.

Basically when I select that server (in this instance, "Lobby"), it gets rid of the server list button. If this server is the first in the list (which I am intending this to be), then the entire list is missing and I am unable to swap between servers.

(provided the embed works correctly)
![image](https://user-images.githubusercontent.com/65716856/131250315-5fd50a8e-99e5-4594-aa95-abb62c77e74e.png)
![image](https://user-images.githubusercontent.com/65716856/131250343-7d9a25b3-cfc9-43e1-a354-f1048a371cfe.png)
Here is an example of the lobby at the top of the server list, and no other servers are showing up in the top right. (this server only has one world rendered in Surface view, that is working OK.

![image](https://user-images.githubusercontent.com/65716856/131250537-73a6eeea-3250-4372-b365-714a7821d452.png)
![image](https://user-images.githubusercontent.com/65716856/131250570-48c49ad1-05ab-457c-bd2d-d9e6a9962433.png)
Here is the "Debug" server at the top of that config list, and now the server list is active and working.

![image](https://user-images.githubusercontent.com/65716856/131250397-e4db0bad-aada-42b7-b9b1-d40c574b71c8.png)
Swapping to the "Lobby" server makes the button vanish, but the list is still there.

I've tried swapping the links from /lobby/ to /smp/ (another server in the cluster) and it picks up the "SMP" server and displays all those elements fine, with the server button there.
Watching inspect element when swapping to the "Lobby" instance turns that button into a comment tag

Hopefully that explains everything and its an easy configuration fix/user error :P

(edit: one of the embeds decided to not want to display correctly, thanks windows snip & sketch)

**Comment by JLyne** [comment] 2021-08-31 14:12
This is a bug in 1.3.2 caused by having a server with a single map defined. The single map hides the maps button, making the server list inaccessible.

2.0.0-beta.2 contains the fix for this if you are comfortable using a beta.

**Closed by JLyne** 2021-08-31 14:12 UTC
Labels: bug
